/*
	AUTOGENERATED FILE

	This file was automatically generated by the model generator tool.
*/
#pragma once
#include "pos.h"

namespace Cube
{
	position points[8] = {
		position{1.000,1.000,-1.000},
		position{1.000,-1.000,-1.000},
		position{1.000,1.000,1.000},
		position{1.000,-1.000,1.000},
		position{-1.000,1.000,-1.000},
		position{-1.000,-1.000,-1.000},
		position{-1.000,1.000,1.000},
		position{-1.000,-1.000,1.000},
	};

	vertex edges[24] = {
		vertex{1,5},
		vertex{5,7},
		vertex{7,3},
		vertex{3,1},
		vertex{4,3},
		vertex{3,7},
		vertex{7,8},
		vertex{8,4},
		vertex{8,7},
		vertex{7,5},
		vertex{5,6},
		vertex{6,8},
		vertex{6,2},
		vertex{2,4},
		vertex{4,8},
		vertex{8,6},
		vertex{2,1},
		vertex{1,3},
		vertex{3,4},
		vertex{4,2},
		vertex{6,5},
		vertex{5,1},
		vertex{1,2},
		vertex{2,6},
	};
}
