/*
	AUTOGENERATED FILE

	This file was automatically generated by the model generator tool.
*/
#pragma once
#include "pos.h"

namespace Cube
{
	position points[8] = {
		position{15.000,15.000,-15.000},
		position{15.000,-15.000,-15.000},
		position{15.000,15.000,15.000},
		position{15.000,-15.000,15.000},
		position{-15.000,15.000,-15.000},
		position{-15.000,-15.000,-15.000},
		position{-15.000,15.000,15.000},
		position{-15.000,-15.000,15.000},
	};

	vertex edges[12] = {
		vertex{1,5},
		vertex{5,7},
		vertex{7,3},
		vertex{3,1},
		vertex{4,3},
		vertex{7,8},
		vertex{8,4},
		vertex{5,6},
		vertex{6,8},
		vertex{6,2},
		vertex{2,4},
		vertex{2,1},
	};
}
